name: 'Execution Flow'

on:
  workflow_dispatch:

jobs:
  lint_and_build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Lint and Build'
        run: |
          echo "Linting and Building..."
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - name: 'Run Unit Tests'
        run: echo "Running Unit Tests"
  deploy_dev:
    runs-on: ubuntu-latest
    needs:
      - lint_and_build
      - unit_tests
    steps:
      - name: 'Deploy to Development'
        run: echo "Deploying to Development"
  e2e_tests:
    runs-on: ubuntu-latest
    needs:
      - deploy_dev
    steps:
      - name: 'Run E2E Tests'
        run: echo "Running E2E Tests"
  load_tests:
    runs-on: ubuntu-latest
    needs:
      - deploy_dev
    steps:
      - name: 'Run Load Tests'
        run: echo "Running Load Tests"
  deploy-prod:
    runs-on: ubuntu-latest
    needs:
      - e2e_tests
      - load_tests
    steps:
      - name: Deploy to prod
        run: echo "Deploying to prod..."
