name: 'Execution Flow'

on:
  push:

jobs:
  lint_and_build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Lint and Build'
        run: |
          echo "Linting and Building..."
          exit 1
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - name: 'Lint and Build'
        run: echo "Linting and Building..."
  deploy_dev:
    runs-on: ubuntu-latest
    needs:
      - lint_and_build
      - unit_tests
    steps:
      - name: 'Deploying to Development'
        run: echo "Deploying to Development"
  e2e_tests:
    runs-on: ubuntu-latest
    needs:
      - deploy_dev
    steps:
      - name: 'Running E2E Tests'
        run: echo "Running E2E Tests"
  load_tests:
    runs-on: ubuntu-latest
    needs:
      - deploy_dev
    steps:
      - name: 'Running Load Tests'
        run: echo "Running Load Tests"
  deploy-prod:
    runs-on: ubuntu-latest
    needs:
      - e2e_tests
      - load_tests
    steps:
      - name: Deploying to prod
        run: echo "Deploying to prod..."
